/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Barbucha Studio (https://sketchfab.com/lukinec)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/9fe7d680d62e470b8810524f712f9cb5
title: Vojna Hill 02c
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    mesh_0: THREE.Mesh
    mesh_1: THREE.Mesh
    mesh_2: THREE.Mesh
    mesh_3: THREE.Mesh
    mesh_4: THREE.Mesh
    mesh_5: THREE.Mesh
    mesh_6: THREE.Mesh
    mesh_7: THREE.Mesh
    mesh_8: THREE.Mesh
    mesh_9: THREE.Mesh
    mesh_10: THREE.Mesh
    mesh_11: THREE.Mesh
    mesh_12: THREE.Mesh
  }
  materials: {
    material0: THREE.MeshStandardMaterial
  }
}

export default function Rocks(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/rocks/scene.gltf') as GLTFResult

  console.log(materials)

  window.rocks = group

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[10000, 10000, 10000]}>
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_0.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_1.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_2.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_3.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_4.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_5.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_6.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_7.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_8.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_9.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_10.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_11.geometry}
            />
            <mesh
              material={materials.material0}
              geometry={nodes.mesh_12.geometry}
            />
          </group>
        </group>
      </group>
    </group>
  )
}
