/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    Pedestral_1: THREE.Mesh
    Pedestral_2: THREE.Mesh
    Pedestral_3: THREE.Mesh
    Pedestral_4: THREE.Mesh
    Pedestral_5: THREE.Mesh
    Floor: THREE.Mesh
    Pillard_1: THREE.Mesh
    Pillard_2: THREE.Mesh
    Pillard_3: THREE.Mesh
    Pillard_4: THREE.Mesh
    Roof: THREE.Mesh
  }
  materials: {}
}

export default function SafeplaceTest(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { scene, nodes, materials } = useGLTF('/models/safeplace-test.glb') as GLTFResult

  console.log(scene)
  console.log(nodes)

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.92, 5.09, -132.57]}>
        <mesh
          material={nodes.Pedestral_1.material}
          geometry={nodes.Pedestral_1.geometry}
          position={[-0.92, -0.73, -0.19]}
        />
      </group>
      <group position={[-23.58, 5.09, -65.07]}>
        <mesh
          material={nodes.Pedestral_2.material}
          geometry={nodes.Pedestral_2.geometry}
          position={[-0.92, -0.73, -0.19]}
        />
      </group>
      <group position={[-63.02, 5.09, -103.89]}>
        <mesh
          material={nodes.Pedestral_3.material}
          geometry={nodes.Pedestral_3.geometry}
          position={[-0.92, -0.73, -0.19]}
        />
      </group>
      <group position={[25.66, 5.09, -91.96]}>
        <mesh
          material={nodes.Pedestral_4.material}
          geometry={nodes.Pedestral_4.geometry}
          position={[-0.92, -0.73, -0.19]}
        />
      </group>
      <group position={[53.62, 5.09, -46.51]}>
        <mesh
          material={nodes.Pedestral_5.material}
          geometry={nodes.Pedestral_5.geometry}
          position={[-0.92, -0.73, -0.19]}
        />
      </group>
      <mesh
        material={nodes.Floor.material}
        geometry={nodes.Floor.geometry}
        position={[0, 0.44, 0]}
        scale={[20.31, 0.4, 10.18]}
      />
      <mesh material={nodes.Pillard_1.material} geometry={nodes.Pillard_1.geometry} position={[19.32, 7.24, 9.18]} />
      <mesh material={nodes.Pillard_2.material} geometry={nodes.Pillard_2.geometry} position={[-19.3, 7.24, 9.18]} />
      <mesh material={nodes.Pillard_3.material} geometry={nodes.Pillard_3.geometry} position={[19.32, 7.24, -9.18]} />
      <mesh material={nodes.Pillard_4.material} geometry={nodes.Pillard_4.geometry} position={[-19.3, 7.24, -9.18]} />
      <mesh
        material={nodes.Roof.material}
        geometry={nodes.Roof.geometry}
        position={[0, 14.04, 0]}
        scale={[20.31, 0.4, 10.18]}
      />
    </group>
  )
}
