/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'
import SafeplacePedestal from '@/components/Safeplace/SafeplacePedestal'
import { SafeplacePOI } from '@/stores/useSafeplaceStore'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    Cube003: THREE.Mesh
    Cube004: THREE.Mesh
    Floor: THREE.Mesh
    Pillard_1: THREE.Mesh
    Pillard_2: THREE.Mesh
    Pillard_3: THREE.Mesh
    Pillard_4: THREE.Mesh
    Roof: THREE.Mesh
  }
  materials: {}
}

export default function SafeplaceModel(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/models/safeplace.glb') as GLTFResult

  return (
    <group ref={group} {...props} dispose={null}>
      <SafeplacePedestal
        safeplacePOI={SafeplacePOI.Pedestal1}
        pedestalObj={nodes.Cube}
      />
      <SafeplacePedestal
        safeplacePOI={SafeplacePOI.Pedestal2}
        pedestalObj={nodes.Cube001}
      />
      <SafeplacePedestal
        safeplacePOI={SafeplacePOI.Pedestal3}
        pedestalObj={nodes.Cube002}
      />
      <SafeplacePedestal
        safeplacePOI={SafeplacePOI.Pedestal4}
        pedestalObj={nodes.Cube003}
      />
      <SafeplacePedestal
        safeplacePOI={SafeplacePOI.Pedestal5}
        pedestalObj={nodes.Cube004}
      />
      <mesh
        material={nodes.Floor.material}
        geometry={nodes.Floor.geometry}
        position={nodes.Floor.position}
        scale={nodes.Floor.scale}
      />

      <mesh
        material={nodes.Pillard_1.material}
        geometry={nodes.Pillard_1.geometry}
        position={nodes.Pillard_1.position}
        scale={nodes.Pillard_1.scale}
      />
      <mesh
        material={nodes.Pillard_2.material}
        geometry={nodes.Pillard_2.geometry}
        scale={nodes.Pillard_2.scale}
        position={nodes.Pillard_2.position}
      />
      <mesh
        material={nodes.Pillard_3.material}
        geometry={nodes.Pillard_3.geometry}
        scale={nodes.Pillard_3.scale}
        position={nodes.Pillard_3.position}
      />
      <mesh
        material={nodes.Pillard_4.material}
        geometry={nodes.Pillard_4.geometry}
        scale={nodes.Pillard_4.scale}
        position={nodes.Pillard_4.position}
      />
      <mesh
        material={nodes.Roof.material}
        geometry={nodes.Roof.geometry}
        position={nodes.Roof.position}
        scale={nodes.Roof.scale}
      />
    </group>
  )
}

useGLTF.preload('/models/safeplace.glb')
